### ISSUE TITLE
"errorType": "InvocationError", "Null check operator used on a null value",

### ISSUE THREAD

**Issue by henryqum** [myConsciousness/aws-lambda-dart-runtime-ns#1]
Hi,

i came across your package and i want to thank you for your work

i deployed a function and i got the following error 

```Test Event Name
NewEve

Response
{
  "errorType": "InvocationError",
  "errorMessage": "Null check operator used on a null value",
  "stackTrace": "#0      new RuntimeContext.fromNextInvocation (package:aws_lambda_dart_runtime_ns/src/runtime/context.dart:56)\n#1      AwsLambdaRuntime.invoke (package:aws_lambda_dart_runtime_ns/src/runtime/runtime.dart:59)\n<asynchronous suspension>\n#2      invokeAwsLambdaRuntime (package:aws_lambda_dart_runtime_ns/src/runtime/runtime.dart:20)\n<asynchronous suspension>\n#3      main (file:///root/node-zfs-test/qcp_storage_qs_proc/bin/main.dart:3)\n<asynchronous suspension>\n"
}```

aws have a problem with this line `executionEnv: Platform.environment[_kAWSLambdaExecutionEnv]!` i guess this var not in the env for some reason maybe it's an optional var

thanks for you help

**Comment by henryqum** [comment]
update: the above error it's only happen when you deploy from a zip file when you use docker is not happening, but it still an error so i keep it open

**Comment by myConsciousness** [comment]
Hi @henryqum , sorry for late reply! Is this issue still occurring?

As mentioned in the official awslabs, it's currently recommended to deploy AWS Lambda functions using the Serverless Framework when using Dart.

**Comment by zdirnecamlcs96** [comment]
Hi @henryqum , how did you managed to solve it? Currently I'm facing issue when using Serverless Frameworl, as the dependency require some token to install but I'm not sure where to inject the token with `sls deploy`. Is there any alternative way to deploy it?

EDIT: Found that `AWS_EXECUTION_ENV` is missing when upload with `.zip`. It works after I add a empty `AWS_EXECUTION_ENV` in Configuration.

https://github.com/myConsciousness/aws-lambda-dart-runtime-ns/blob/695c663f1184e1db2866f11d84e4ea175f53883f/lib/src/runtime/context.dart#L56  

EDIT2: I'm using `provided` which is a `OS-only Runtime`. Therefore `AWS_EXECUTION_ENV` is missing.
https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-runtime
<img width="868" height="61" alt="Image" src="https://github.com/user-attachments/assets/40b63e50-3210-4cdb-8d67-72452a8e863f" />
